"""empty message

Revision ID: 010db9a3998d
Revises: 
Create Date: 2020-05-18 12:13:45.066676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010db9a3998d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dokter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=25), nullable=False),
    sa.Column('spesialis', sa.String(length=20), nullable=False),
    sa.Column('noTelepon', sa.String(length=13), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=25), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=20), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=1), nullable=False),
    sa.Column('gol_darah', sa.String(length=1), nullable=False),
    sa.Column('alamat', sa.String(length=100), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Jadwal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hari', sa.String(length=25), nullable=False),
    sa.Column('jamMulai', sa.Time(), nullable=False),
    sa.Column('jamSelesai', sa.Time(), nullable=False),
    sa.Column('dokterId', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['dokterId'], ['Dokter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('profileId', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['profileId'], ['Profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('profileId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('Jadwal')
    op.drop_table('Profiles')
    op.drop_table('Dokter')
    # ### end Alembic commands ###
