"""empty message

Revision ID: 015095395978
Revises: 615d786ac336
Create Date: 2020-05-13 15:09:38.570038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '015095395978'
down_revision = '615d786ac336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='Users')
    op.drop_column('Users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('username', mysql.VARCHAR(length=80), nullable=False))
    op.create_index('username', 'Users', ['username'], unique=True)
    # ### end Alembic commands ###
